### ISSUE TITLE
Django 1.8 support

### ISSUE THREAD

**Issue by chhantyal** [torchbox/django-modelcluster#25]
I am getting this error while trying to use with 1.8.

````
ImportError: cannot import name RelatedObject
````

**Comment by kaedroho** [comment]
Have you tried the Django 1.8 branch? (https://github.com/torchbox/django-modelcluster/pull/24) (awaiting review)

**Comment by chhantyal** [comment]
Thanks for letting me know. Github used to show issues and PR on same tab, now it seems to have reverted - so missed that PR. 

I will try that.
