### ISSUE TITLE
AttributeError: 'ModelName' object has no attribute '+'

### ISSUE THREAD

**Issue by jasonm** [torchbox/django-modelcluster#49]
Hi folks!  I find that suppressing a backwards relation to a subclass of ModelCluster appears to cause an issue when saving the parent model.  I hope this is the right place to open an issue.

Here's the full backtrace from our app and some related model code: https://gist.github.com/jasonm/a6f514026bc2b97c1b94

In the Wagtail CMS I'm working on, an `Event` is tagged with `EventLanguageTag` and `EventRegionTag` instances and the backwards relation is suppressed by specifying `related_name='+'`:

```python
class EventLanguageTag(TaggedItemBase):
    content_object = ParentalKey('cms.Event', related_name='+')

class EventRegionTag(TaggedItemBase):
    content_object = ParentalKey('cms.Event', related_name='+')

@register_snippet
class Event(ClusterableModel, index.Indexed):
    language_tags = TaggableManager(through=EventLanguageTag, blank=True, related_name="event_language", verbose_name="Languages")
    region_tags = TaggableManager(through=EventRegionTag, blank=True, related_name="event_region", verbose_name="Regions")
    # ...
```

This causes `django-modelcluster` to look for relations named `+`:

```python
# shell_plus session
In [13]: from modelcluster.models import get_all_child_relations

In [14]: get_all_child_relations(Event())
Out[14]: [<ManyToOneRel: cms.eventlanguagetag>, <ManyToOneRel: cms.eventregiontag>]

In [15]: [rel.get_accessor_name() for rel in get_all_child_relations(Event())]
Out[15]: [u'+', u'+']
```

which it then cannot find to save at https://github.com/torchbox/django-modelcluster/blob/eca7709065a6f82914ba47268e0127dbc8f6fe1a/modelcluster/models.py#L201

This is on Django 1.8.4, wagtail 1.2, django-taggit 0.17.1, django-modelcluster 1.1

**Comment by gasman** [comment]
Hi @jasonm,
Setting `related_name='+'` on a ParentalKey is deliberately not supported - the entire purpose of django-modelcluster is to provide ways to access child models through the parent, so suppressing the backwards relation would not ever be meaningful. Even if you're not using the relation directly, django-modelcluster's internals rely extensively on the relation name.

Arguably what we should be doing is adding an explicit check to disallow `related_name='+'`...

**Comment by jasonm** [comment]
@gasman thanks for the response and explanation, that totally makes sense.  Thanks for fixing @kaedroho!
